### PR TITLE
add gearman-status

### PR DESCRIPTION
**Pull request by jiancheung**

### CODE REVIEW

**Comment by dfuentes** [comment]
What's the use case here?  We don't want to encourage people docker exec'ing on slave boxes.

**Comment by jiancheung** [comment]
My use case is that I docker exec on slave boxes to check gearman-status (are my workers actually attached? did jobs submit correctly? how many jobs are running?)

**Comment by dfuentes** [comment]
But why can't you do that remotely (for example, https://gist.github.com/dfuentes/8f33374ae76c9ea79380)?

**Comment by jiancheung** [comment]
Because I didn't know about that script. Thanks :)

**Comment by jiancheung** [comment]
closing in favor of the script.

**Pull request closed without merging**
